"""Deterministic OPC archives for the optional Lib3MF capability experiment."""

from __future__ import annotations

import io
import zipfile
from dataclasses import dataclass

from tests.factories.geometry import expanding_three_mf, tetrahedron, three_mf

CORE = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
PRODUCTION = "http://schemas.microsoft.com/3dmanufacturing/production/2015/06"
IDENTITY = "1 0 0 0 1 0 0 0 1 0 0 0"


@dataclass(frozen=True)
class PilotCase:
    name: str
    payload: bytes
    expected: dict
    max_faces: int = 2_000_000


def opc_package(payload: bytes, *, mutations: dict[str, bytes] | None = None) -> bytes:
    """Add required OPC structure and freeze archive metadata, not source XML."""
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        entries = {name: archive.read(name) for name in archive.namelist()}
    entries.setdefault(
        "[Content_Types].xml",
        b'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        b'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        b'<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
        b"</Types>",
    )
    entries.setdefault(
        "_rels/.rels",
        b'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        b'<Relationship Id="model" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" Target="/3D/3dmodel.model"/>'
        b"</Relationships>",
    )
    entries.update(mutations or {})
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in sorted(entries.items()):
            info = zipfile.ZipInfo(name, date_time=(2020, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, data)
    return stream.getvalue()


def _model(payload: bytes) -> bytes:
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        return archive.read("3D/3dmodel.model")


def corpus() -> tuple[PilotCase, ...]:
    import numpy as np

    ready = {"outcome": "ready", "faces": 4, "instances": 1, "bbox": [10, 20, 30]}
    refused = {"outcome": "refused"}
    base = three_mf()
    cases = [PilotCase("core-basic", opc_package(base), ready)]
    scales = {
        "micron": 0.001,
        "millimeter": 1,
        "centimeter": 10,
        "inch": 25.4,
        "foot": 304.8,
        "meter": 1000,
    }
    for unit, scale in scales.items():
        cases.append(
            PilotCase(
                "unit-" + unit,
                opc_package(three_mf(unit=unit)),
                {**ready, "bbox": [10 * scale, 20 * scale, 30 * scale]},
            )
        )
    cases.append(
        PilotCase("unit-unsupported", opc_package(three_mf(unit="yard")), refused)
    )
    cases.append(
        PilotCase(
            "nested-reflection",
            opc_package(
                three_mf(
                    unit="inch",
                    assemblies={2: [(1, "-2 0 0 0 2 0 0 0 2 3 4 5")]},
                    build=((2, "1 0 0 0 1 0 0 0 1 100 200 300"),),
                )
            ),
            {
                **ready,
                "bbox": [508, 1016, 1524],
                "minimum": [2108.2, 5181.6, 7747],
                "volume": 1000 * 25.4**3 * 8,
            },
        )
    )
    cases.append(
        PilotCase(
            "build-multiple",
            opc_package(three_mf(build=((1, None), (1, "1 0 0 0 1 0 0 0 1 50 0 0")))),
            {**ready, "faces": 8, "instances": 2, "bbox": [60, 20, 30]},
        )
    )
    for flag in ("false", "0"):
        xml = _model(three_mf(build=((1, None), (1, "1 0 0 0 1 0 0 0 1 50 0 0"))))
        xml = xml.replace(
            b'<item objectid="1" transform=',
            b'<item printable="' + flag.encode() + b'" objectid="1" transform=',
        )
        cases.append(
            PilotCase(
                "printable-" + flag,
                opc_package(base, mutations={"3D/3dmodel.model": xml}),
                ready,
            )
        )
    cases.append(
        PilotCase(
            "root-relationship",
            opc_package(
                three_mf(
                    model_part="3D/custom.model", relationship_target="/3D/custom.model"
                )
            ),
            ready,
        )
    )
    child = _model(base)
    main = _model(
        three_mf(
            meshes={},
            assemblies={2: [(1, None)]},
            build=((2, None),),
            external_paths={1: "/3D/child.model"},
        )
    )
    # UUIDs required by the Production extension are stable, not generated by the reader.
    main = main.replace(
        b"<model ",
        b'<model xmlns:p="' + PRODUCTION.encode() + b'" requiredextensions="p" ',
        1,
    )
    main = main.replace(
        b'<object id="2"',
        b'<object p:UUID="00000000-0000-4000-8000-000000000002" id="2"',
    )
    main = main.replace(
        b"<component ", b'<component p:UUID="00000000-0000-4000-8000-000000000003" ', 1
    )
    main = main.replace(
        b"<build>", b'<build p:UUID="00000000-0000-4000-8000-000000000004">'
    ).replace(b"<item ", b'<item p:UUID="00000000-0000-4000-8000-000000000005" ', 1)
    relationships = b'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="child" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" Target="/3D/child.model"/></Relationships>'
    production = opc_package(
        base,
        mutations={
            "3D/3dmodel.model": main,
            "3D/child.model": child,
            "3D/_rels/3dmodel.model.rels": relationships,
        },
    )
    cases.append(PilotCase("production-external", production, ready))
    unknown = _model(base).replace(
        b"<model ",
        b'<model xmlns:q="urn:printstash:unknown" requiredextensions="q" ',
        1,
    )
    cases.append(
        PilotCase(
            "unknown-required-extension",
            opc_package(base, mutations={"3D/3dmodel.model": unknown}),
            refused,
        )
    )
    malformed = _model(base).replace(b'x="0.0"', b'x="nan"', 1)
    cases.append(
        PilotCase(
            "nonfinite-vertex",
            opc_package(base, mutations={"3D/3dmodel.model": malformed}),
            refused,
        )
    )
    dangling = _model(base).replace(b'v1="0"', b'v1="99"', 1)
    cases.append(
        PilotCase(
            "invalid-face-index",
            opc_package(base, mutations={"3D/3dmodel.model": dangling}),
            refused,
        )
    )
    duplicate = _model(base).replace(
        b"</resources>",
        _model(base).split(b"<resources>")[1].split(b"</resources>")[0]
        + b"</resources>",
    )
    cases.append(
        PilotCase(
            "duplicate-object-id",
            opc_package(base, mutations={"3D/3dmodel.model": duplicate}),
            refused,
        )
    )
    for name, transform in (
        ("singular-transform", "1 0 0 0 0 0 0 0 1 0 0 0"),
        ("nonfinite-transform", "nan 0 0 0 1 0 0 0 1 0 0 0"),
    ):
        cases.append(
            PilotCase(name, opc_package(three_mf(build=((1, transform),))), refused)
        )
    cases.append(
        PilotCase(
            "reachable-cycle",
            opc_package(
                three_mf(meshes={}, assemblies={1: [(2, None)], 2: [(1, None)]})
            ),
            refused,
        )
    )
    unused = tetrahedron()
    unused.vertices[0, 0] = np.nan
    cases.append(
        PilotCase(
            "unreachable-invalid-resource",
            opc_package(three_mf(meshes={1: tetrahedron(), 9: unused})),
            ready,
        )
    )
    cases.append(
        PilotCase(
            "unreachable-invalid-part",
            opc_package(three_mf(extras={"3D/unused.model": b"broken<xml"})),
            ready,
        )
    )
    cases.append(
        PilotCase(
            "expanded-budget",
            opc_package(three_mf(build=((1, None),) * 3)),
            refused,
            max_faces=8,
        )
    )
    cases.append(PilotCase("exact-budget", opc_package(base), ready, max_faces=4))
    cases.append(
        PilotCase(
            "exponential-expansion", opc_package(expanding_three_mf(depth=20)), refused
        )
    )
    unused_vertex = _model(base).replace(
        b"</vertices>", b'<vertex x="1000" y="1000" z="1000"/></vertices>'
    )
    cases.append(
        PilotCase(
            "unused-vertex",
            opc_package(base, mutations={"3D/3dmodel.model": unused_vertex}),
            ready,
        )
    )
    remote = tetrahedron()
    remote.vertices += np.array([1e9, 1e9, 1e9])
    cases.append(
        PilotCase(
            "large-coordinate-precision",
            opc_package(three_mf(meshes={1: remote})),
            {**ready, "minimum": [1e9, 1e9, 1e9]},
        )
    )
    empty = _model(base).replace(b'<triangle v1="0" v2="2" v3="1" />', b"")
    cases.append(
        PilotCase(
            "open-surface",
            opc_package(base, mutations={"3D/3dmodel.model": empty}),
            {**ready, "faces": 3},
        )
    )
    return tuple(cases)


def load_case(name: str) -> PilotCase:
    return next(case for case in corpus() if case.name == name)


def load_mesh(face_count: int, instances: int = 1) -> PilotCase:
    import numpy as np
    import trimesh

    if face_count < 4 or face_count % 4 or instances < 1:
        raise ValueError("invalid_pilot_load")
    copies = face_count // 4
    mesh = tetrahedron()
    vertices = np.tile(mesh.vertices, (copies, 1))
    # Disconnected tetrahedra exercise distinct coordinates without degenerate faces.
    vertices[:, 0] += np.repeat(np.arange(copies) * 20, 4)
    faces = (
        np.tile(mesh.faces, (copies, 1)) + np.repeat(np.arange(copies) * 4, 4)[:, None]
    )
    combined = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
    payload = opc_package(
        three_mf(meshes={1: combined}, build=((1, None),) * instances)
    )
    return PilotCase(
        f"load-{face_count}-copies-{instances}",
        payload,
        {
            "outcome": "ready",
            "faces": face_count * instances,
            "instances": instances,
            "bbox": [(copies - 1) * 20 + 10, 20, 30],
        },
    )
