"""add artifact cache policy

Revision ID: 00cb0e8975d1
Revises: 36872a2fc034
Create Date: 2026-09-09 03:03:08.116066

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00cb0e8975d1"
down_revision: Union[str, Sequence[str], None] = "36872a2fc034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("artifact_cache_policy_json", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("artifact_cache_policy_json")

    # ### end Alembic commands ###
