"""record bounded capacity and audit aggregates

Revision ID: 321c51b5aa8e
Revises: d6e9d78801ef
Create Date: 2026-09-08 16:40:44.954214

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '321c51b5aa8e'
down_revision: Union[str, Sequence[str], None] = 'd6e9d78801ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity_admission_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('operation_kind', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('required_bytes', sa.BigInteger(), nullable=False),
    sa.Column('available_bytes', sa.BigInteger(), nullable=True),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('headroom_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capacity_admission_events'))
    )
    with op.batch_alter_table('capacity_admission_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capacity_admission_events_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_admission_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_admission_events_operation_kind'), ['operation_kind'], unique=False)

    with op.batch_alter_table('vault_audit_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unclaimed_bytes', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('unclaimed_unknown_size_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_audit_runs', schema=None) as batch_op:
        batch_op.drop_column('unclaimed_unknown_size_count')
        batch_op.drop_column('unclaimed_bytes')

    with op.batch_alter_table('capacity_admission_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capacity_admission_events_operation_kind'))
        batch_op.drop_index(batch_op.f('ix_capacity_admission_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_capacity_admission_events_decision'))

    op.drop_table('capacity_admission_events')
    # ### end Alembic commands ###
