"""scheduled vault audit policies and events

Revision ID: 4b21cbe868b6
Revises: 9cbee9215a34
Create Date: 2026-09-07 21:36:30.352163

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b21cbe868b6'
down_revision: Union[str, Sequence[str], None] = '9cbee9215a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Native PostgreSQL enums require extending the existing type explicitly.
    # SQLite's generated batch below updates its string representation.
    if op.get_bind().dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'STORAGE_REGRESSION'")
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'STORAGE_RECOVERY'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_audit_policies',
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('month_day', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('bytes_per_second', sa.Integer(), nullable=False),
    sa.Column('read_concurrency', sa.Integer(), nullable=False),
    sa.Column('auto_repair', sa.Boolean(), nullable=False),
    sa.Column('repair_actions_json', sa.Text(), nullable=False),
    sa.Column('full_cost_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('deferred_reason', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_vault_audit_policies_requested_by_users')),
    sa.PrimaryKeyConstraint('mode', name=op.f('pk_vault_audit_policies'))
    )
    with op.batch_alter_table('vault_audit_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_audit_policies_next_due_at'), ['next_due_at'], unique=False)

    op.create_table('vault_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['vault_audit_runs.id'], name=op.f('fk_vault_audit_events_run_id_vault_audit_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_audit_events')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_vault_audit_events_dedup_key'))
    )
    with op.batch_alter_table('vault_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_audit_events_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('PRINT_COMPLETED', 'PRINT_FAILED', 'PRINT_CANCELLED', 'PRINTER_OFFLINE', 'STORAGE_REGRESSION', 'STORAGE_RECOVERY', name='notificationeventtype'),
               existing_nullable=False)

    with op.batch_alter_table('vault_audit_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_slot', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('trigger', sa.String(length=16), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('trigger_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('policy_revision', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deadline_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bytes_per_second', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bytes_read', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('storage_generation', sa.String(length=64), server_default='', nullable=False))
        batch_op.add_column(sa.Column('scope', sa.String(length=32), server_default='vault', nullable=False))
        batch_op.add_column(sa.Column('baseline_run_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('regression_json', sa.Text(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('result_recorded', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('repair_actions_json', sa.Text(), server_default='[]', nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_vault_audit_runs_active_slot'), ['active_slot'])
        batch_op.create_unique_constraint(batch_op.f('uq_vault_audit_runs_trigger_key'), ['trigger_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_audit_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vault_audit_runs_trigger_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vault_audit_runs_active_slot'), type_='unique')
        batch_op.drop_column('repair_actions_json')
        batch_op.drop_column('result_recorded')
        batch_op.drop_column('regression_json')
        batch_op.drop_column('baseline_run_id')
        batch_op.drop_column('scope')
        batch_op.drop_column('storage_generation')
        batch_op.drop_column('bytes_read')
        batch_op.drop_column('bytes_per_second')
        batch_op.drop_column('deadline_at')
        batch_op.drop_column('scheduled_for')
        batch_op.drop_column('policy_revision')
        batch_op.drop_column('trigger_key')
        batch_op.drop_column('trigger')
        batch_op.drop_column('active_slot')

    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('PRINT_COMPLETED', 'PRINT_FAILED', 'PRINT_CANCELLED', 'PRINTER_OFFLINE', 'STORAGE_REGRESSION', 'STORAGE_RECOVERY', name='notificationeventtype'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('vault_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_audit_events_run_id'))

    op.drop_table('vault_audit_events')
    with op.batch_alter_table('vault_audit_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_audit_policies_next_due_at'))

    op.drop_table('vault_audit_policies')
    # ### end Alembic commands ###
