"""fence derivative attempt publication

Revision ID: 67494831ae72
Revises: f1e72b50f1cc
Create Date: 2026-10-04 14:11:53.687870

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67494831ae72"
down_revision: Union[str, Sequence[str], None] = "f1e72b50f1cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Legacy workers have no ownership token; retain their published outputs
    # and return interrupted work to retry without consuming its attempt budget.
    op.execute(
        sa.text(
            "UPDATE artifact_derivatives SET state = 'failed', "
            "failure_reason = 'attempt_interrupted', next_attempt_at = NULL, "
            "attempts = CASE WHEN attempts > 0 THEN attempts - 1 ELSE 0 END "
            "WHERE state = 'running'"
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifact_derivatives", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("attempt_token", sa.String(length=36), nullable=True)
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_artifact_derivatives_attempt_token_iff_running"),
            "(state = 'running') = (attempt_token IS NOT NULL)",
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("execution_epoch", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("submitted_epoch", sa.String(length=64), nullable=True)
        )
    # Job IDs identify a nonempty initial epoch without inventing a submitted
    # execution. Old engine callbacks omit the epoch and are safely declined.
    op.execute(
        sa.text(
            "UPDATE jobs SET execution_epoch = id, "
            "submitted_epoch = CASE WHEN attempts > 0 THEN id ELSE NULL END"
        )
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "execution_epoch", existing_type=sa.String(length=64), nullable=False
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_jobs_execution_epoch_present"), "length(execution_epoch) > 0"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_jobs_submitted_epoch_present"),
            "submitted_epoch IS NULL OR length(submitted_epoch) > 0",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_jobs_submitted_epoch_present"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_jobs_execution_epoch_present"), type_="check"
        )
        batch_op.drop_column("submitted_epoch")
        batch_op.drop_column("execution_epoch")

    with op.batch_alter_table("artifact_derivatives", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_artifact_derivatives_attempt_token_iff_running"),
            type_="check",
        )
        batch_op.drop_column("attempt_token")

    # ### end Alembic commands ###
