"""complete audit policy controls and operational events

Revision ID: 71bd0ebbf381
Revises: 4b21cbe868b6
Create Date: 2026-09-07 23:21:58.895566

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71bd0ebbf381'
down_revision: Union[str, Sequence[str], None] = '4b21cbe868b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Native PostgreSQL enum additions are not detected by autogenerate.
    if op.get_bind().dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            for label in ("STORAGE_AUDIT_FAILED", "STORAGE_AUDIT_CANCELLED", "STORAGE_AUDIT_OVERDUE", "STORAGE_REPAIR_FAILED"):
                op.execute(f"ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS '{label}'")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('PRINT_COMPLETED', 'PRINT_FAILED', 'PRINT_CANCELLED', 'PRINTER_OFFLINE', 'STORAGE_REGRESSION', 'STORAGE_RECOVERY', name='notificationeventtype'),
               type_=sa.Enum('PRINT_COMPLETED', 'PRINT_FAILED', 'PRINT_CANCELLED', 'PRINTER_OFFLINE', 'STORAGE_REGRESSION', 'STORAGE_RECOVERY', 'STORAGE_AUDIT_FAILED', 'STORAGE_AUDIT_CANCELLED', 'STORAGE_AUDIT_OVERDUE', 'STORAGE_REPAIR_FAILED', name='notificationeventtype'),
               existing_nullable=False)

    with op.batch_alter_table('vault_audit_events', schema=None) as batch_op:
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vault_audit_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jitter_seconds', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('max_lateness_minutes', sa.Integer(), server_default='120', nullable=False))
        batch_op.add_column(sa.Column('notification_threshold', sa.String(length=16), server_default='warning', nullable=False))
        batch_op.add_column(sa.Column('notification_channels_json', sa.Text(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('notification_cooldown_minutes', sa.Integer(), server_default='60', nullable=False))
        batch_op.add_column(sa.Column('last_notified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retry_after', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('launch_failures', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('vault_audit_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_bytes', sa.BigInteger(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema, discarding only policy-only overdue event evidence."""
    op.execute("DELETE FROM vault_audit_events WHERE run_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_audit_runs', schema=None) as batch_op:
        batch_op.drop_column('planned_bytes')

    with op.batch_alter_table('vault_audit_policies', schema=None) as batch_op:
        batch_op.drop_column('launch_failures')
        batch_op.drop_column('retry_after')
        batch_op.drop_column('last_notified_at')
        batch_op.drop_column('notification_cooldown_minutes')
        batch_op.drop_column('notification_channels_json')
        batch_op.drop_column('notification_threshold')
        batch_op.drop_column('max_lateness_minutes')
        batch_op.drop_column('jitter_seconds')

    with op.batch_alter_table('vault_audit_events', schema=None) as batch_op:
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('PRINT_COMPLETED', 'PRINT_FAILED', 'PRINT_CANCELLED', 'PRINTER_OFFLINE', 'STORAGE_REGRESSION', 'STORAGE_RECOVERY', 'STORAGE_AUDIT_FAILED', 'STORAGE_AUDIT_CANCELLED', 'STORAGE_AUDIT_OVERDUE', 'STORAGE_REPAIR_FAILED', name='notificationeventtype'),
               type_=sa.Enum('PRINT_COMPLETED', 'PRINT_FAILED', 'PRINT_CANCELLED', 'PRINTER_OFFLINE', 'STORAGE_REGRESSION', 'STORAGE_RECOVERY', name='notificationeventtype'),
               existing_nullable=False)

    # ### end Alembic commands ###
