"""add durable capacity reservations and inventory samples

Revision ID: 9cbee9215a34
Revises: 0a6b1f868ae0
Create Date: 2026-09-07 21:34:52.549787

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9cbee9215a34'
down_revision: Union[str, Sequence[str], None] = '0a6b1f868ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capacity_locks'))
    )
    op.create_table('capacity_reservations',
    sa.Column('operation_id', sa.String(length=200), nullable=False),
    sa.Column('resources_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id', name=op.f('pk_capacity_reservations'))
    )
    with op.batch_alter_table('capacity_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capacity_reservations_expires_at'), ['expires_at'], unique=False)

    op.create_table('storage_inventory_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('target_ref', sa.String(length=128), nullable=False),
    sa.Column('owned_bytes', sa.BigInteger(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.CheckConstraint('owned_bytes >= 0', name=op.f('ck_storage_inventory_samples_nonnegative_owned_bytes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_inventory_samples'))
    )
    with op.batch_alter_table('storage_inventory_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_inventory_samples_sampled_at'), ['sampled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_inventory_samples_target_ref'), ['target_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_inventory_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_inventory_samples_target_ref'))
        batch_op.drop_index(batch_op.f('ix_storage_inventory_samples_sampled_at'))

    op.drop_table('storage_inventory_samples')
    with op.batch_alter_table('capacity_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capacity_reservations_expires_at'))

    op.drop_table('capacity_reservations')
    op.drop_table('capacity_locks')
    # ### end Alembic commands ###
