"""retain capacity owner process identity for restart reconciliation

Revision ID: d6e9d78801ef
Revises: f1f73ea15eb0
Create Date: 2026-09-07 21:54:47.965907

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6e9d78801ef"
down_revision: Union[str, Sequence[str], None] = "f1f73ea15eb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capacity_reservations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "owner_identity_json", sa.Text(), server_default="{}", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capacity_reservations", schema=None) as batch_op:
        batch_op.drop_column("owner_identity_json")

    # ### end Alembic commands ###
