"""Persist first viewer demand and expand derivative/Job CHECKs for STL previews.

Revision ID: f1e72b50f1cc
Revises: a1d9da54fb03
Create Date: 2026-10-04 11:39:02.590721

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1e72b50f1cc"
down_revision: Union[str, Sequence[str], None] = "a1d9da54fb03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifact_derivatives", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_artifact_derivatives_kind_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_artifact_derivatives_kind_values"),
            "kind IN ('metadata', 'thumbnail', 'toolpath', 'viewer_stl')",
        )

    with op.batch_alter_table(
        "derivative_group_regenerations", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_derivative_group_regenerations_definition_values"),
            type_="check",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_derivative_group_regenerations_definition_values"),
            "definition IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'derivatives.viewer_stl', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
        )
        batch_op.drop_constraint(
            batch_op.f("ck_derivative_group_regenerations_kind_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_derivative_group_regenerations_kind_values"),
            "kind IN ('metadata', 'thumbnail', 'toolpath', 'viewer_stl')",
        )

    with op.batch_alter_table("derivative_regenerations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_derivative_regenerations_kind_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_derivative_regenerations_kind_values"),
            "kind IN ('metadata', 'thumbnail', 'toolpath', 'viewer_stl')",
        )

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("viewer_requested_at", sa.DateTime(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_files_viewer_requested_at"),
            ["viewer_requested_at"],
            unique=False,
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_jobs_kind_values"), type_="check")
        batch_op.create_check_constraint(
            batch_op.f("ck_jobs_kind_values"),
            "kind IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'derivatives.viewer_stl', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
        )

    with op.batch_alter_table("reconcile_cursors", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_reconcile_cursors_source_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_reconcile_cursors_source_values"),
            "source IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'derivatives.viewer_stl', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Only disposable preview work is removed; original files and other Jobs survive.
    op.execute("DELETE FROM artifact_derivatives WHERE kind = 'viewer_stl'")
    op.execute("DELETE FROM derivative_regenerations WHERE kind = 'viewer_stl'")
    op.execute(
        "DELETE FROM derivative_group_regenerations WHERE definition = 'derivatives.viewer_stl' OR kind = 'viewer_stl'"
    )
    op.execute("DELETE FROM reconcile_cursors WHERE source = 'derivatives.viewer_stl'")
    op.execute("DELETE FROM jobs WHERE kind = 'derivatives.viewer_stl'")
    with op.batch_alter_table("reconcile_cursors", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_reconcile_cursors_source_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_reconcile_cursors_source_values"),
            "source IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_jobs_kind_values"), type_="check")
        batch_op.create_check_constraint(
            batch_op.f("ck_jobs_kind_values"),
            "kind IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
        )

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_viewer_requested_at"))
        batch_op.drop_column("viewer_requested_at")

    with op.batch_alter_table("derivative_regenerations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_derivative_regenerations_kind_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_derivative_regenerations_kind_values"),
            "kind IN ('metadata', 'thumbnail', 'toolpath')",
        )

    with op.batch_alter_table(
        "derivative_group_regenerations", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_derivative_group_regenerations_kind_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_derivative_group_regenerations_kind_values"),
            "kind IN ('metadata', 'thumbnail', 'toolpath')",
        )
        batch_op.drop_constraint(
            batch_op.f("ck_derivative_group_regenerations_definition_values"),
            type_="check",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_derivative_group_regenerations_definition_values"),
            "definition IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
        )

    with op.batch_alter_table("artifact_derivatives", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_artifact_derivatives_kind_values"), type_="check"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_artifact_derivatives_kind_values"),
            "kind IN ('metadata', 'thumbnail', 'toolpath')",
        )

    # ### end Alembic commands ###
