"""add configurable storage headroom override

Revision ID: f1f73ea15eb0
Revises: 9cbee9215a34
Create Date: 2026-09-07 21:45:53.904481

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1f73ea15eb0"
down_revision: Union[str, Sequence[str], None] = "9cbee9215a34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("storage_min_free_bytes", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("storage_min_free_bytes")

    # ### end Alembic commands ###
